#!/usr/bin/env python3
"""
Parses Firefox's kBaseFonts_* / kLangPack_* C-string arrays out of
gfxFcPlatformFontList.cpp / StandardFonts-*.inc and emits a C++ header
with unordered_set<string> per array name.

Usage:
    python3 gen_fonts.py gfxFcPlatformFontList.cpp > generated_fonts.h
"""
import re
import sys

# Matches: static const char* kBaseFonts_Ubuntu_20_04[] = { "a", "b", ... };
ARRAY_RE = re.compile(
    r'(?:static\s+)?(?:\[\[maybe_unused\]\]\s*)?const char\*\s*(k\w+)\s*\[\]\s*=\s*\{(.*?)\};',
    re.DOTALL
)
STRING_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')

def parse(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        content = f.read()

    arrays = {}
    for name, body in ARRAY_RE.findall(content):
        fonts = [m.replace('\\"', '"') for m in STRING_RE.findall(body)]
        if fonts:
            arrays[name] = fonts
    return arrays

def emit(arrays):
    print("#pragma once")
    print("// AUTO-GENERATED by gen_fonts.py — do not hand-edit.")
    print("#include <unordered_set>")
    print("#include <string>")
    print()
    for name, fonts in arrays.items():
        var = name[1:]  # strip leading 'k'
        print(f"inline const std::unordered_set<std::string> {var} = {{")
        for font in fonts:
            escaped = font.replace('\\', '\\\\').replace('"', '\\"')
            print(f'    "{escaped}",')
        print("};")
        print()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: gen_fonts.py <file1.cpp> [file2.inc ...]", file=sys.stderr)
        sys.exit(1)

    all_arrays = {}
    for path in sys.argv[1:]:
        all_arrays.update(parse(path))

    if not all_arrays:
        print("// no arrays found — check the regex against your file's format", file=sys.stderr)
        sys.exit(1)

    emit(all_arrays)